name: Build and Release KOT.AI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: |
        go build -v -o kot.exe -ldflags="-H=windowsgui" .

    - name: Verify build
      run: |
        if (-not (Test-Path kot.exe)) {
          Write-Error "Build failed: kot.exe not found"
          exit 1
        }
        Write-Output "Build successful: kot.exe created"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kot-ai-windows
        path: kot.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: kot.exe
        name: KOT.AI ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true